### ISSUE TITLE
package content of each version is not clear

### ISSUE THREAD

**Issue by Yujins** [jins-meme/home#2]

**Comment by kazoo-kmt** [comment]
Is developer version's hardware same as JINS MEME ES? What is the difference between JINS MEME DEVELOPERS and JINS MEME ES?

**Comment by Yujins** [comment]
> Is developer version's hardware same as JINS MEME ES? What is the difference between JINS MEME DEVELOPERS and JINS MEME ES?
YES. "JINS MEME ES" and "JINS MEME DEVELOPERS" are same hardware. However, since the official iOS/Android applications are not available outside Japan, we've named it as  "DEVELOPERS" to show our inention that we sell "JINS MEME DEVELOPERS"  for professional use. e.g.) Development, research, etc

**Comment by DonGateley** [comment]
Requiring a steep developers cost to get a usable one outside of Japan isn't helping development any.
